runtime: nodejs18

# Optional: Handlers for static files if you want App Engine (nginx) to serve them directly
# For simple node apps, letting Node serve them is often easier to configure, but this is more efficient.
handlers:
  - url: /public
    static_dir: public
  - url: /src
    static_dir: src
  - url: /.*
    script: auto
